language: python
python:
  - '2.7'

before_install:
  - "cp script.py test/script.py"

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests

services:
  - mongodb

script: npm install mocha --save-dev; npm install mongoose; npm install mocha-mongoose; npm install chai; npm install chai-fs;npm install supertest;  npm test; python test/test.py
