language: python
python:
  - '2.7'

# command to install dependencies
install: "sudo pip install -r requirements.txt"
# command to run tests

script: npm install mocha --save-dev; npm install mongoose; npm install mocha-mongoose; npm install chai; npm install chai-fs;npm install supertest;  npm test
